#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ruqsana123begum@gmail.com
#    password: zcxb igmi lxui wips
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#          auth: true